# Default values for kyverno-policies.


# GENERAL POLICIES 

# This policy ensures that any user cannot exec inside a pod in any of the namespaces which are not excluded. 

blockPodExecByNamespacePolicy:
  background: false
  validationFailureAction: Audit
  excludedNamespaces:
    - pci
    - default


# This policy ensures that images are only pulled from trusted registries. 

restrictImageRegistriesPolicy:
  background: false
  validationFailureAction: Enforce
  registry: "hub.docker.io/* | bar.io/*"


# Enforce ETCD Encryption

enforceEtcdEncryptionPolicy:
    background: false
    validationFailureAction: Audit


# This policy restricts the binding of the cluster-admin role to any subject. 

restrictBindingClusterAdminPolicy:
    background: false
    validationFailureAction: Audit
    role: "!cluster-admin"


# This policy restricts escalation verbs to be added in a Role

restrictEscalationVerbsPolicy:
  background: false
  validationFailureAction: Audit
  verbs:
      - bind
      - impersonate
      - escalate

# This policy restricts certain actions to be performed on the 'Secret' object, specifically viewing the sensitive data inside the secrets. 

restrictSecretAccessPolicy:
  background: false
  validationFailureAction: Audit
  verbs:
      - list
      - view
      - get


# This policy prevents creating bindings to some of these groups including system:anonymous, system:unauthenticated, and system:masters.
restrictBindingSystemGroupsPolicy:
  background: false
  validationFailureAction: Audit


# This policy blocks any Role or ClusterRole that contains a wildcard entry in the resources list found in any rule.
restrictWildcardResourcesPolicy:
  background: false
  validationFailureAction: Audit


blockUpdatesAndDeletes:
  background: false
  validationFailureAction: Enforce
  excludedNamespaces:
    - test