# Default values for kyverno-policies.


# GENERAL POLICIES 

# Block Pod Exec by Namespace

blockPodExecByNamespacePolicy:
  background: false
  validationFailureAction: Enforce
  excludedNamespaces:
    - pci
    - default


# Restrict Image Registries

restrictImageRegistriesPolicy:
  background: false
  validationFailureAction: Enforce
  registry: "hub.docker.io/* | bar.io/*"


# Enforce ETCD Encryption

enforceEtcdEncryptionPolicy:
    background: false
    validationFailureAction: Enforce


# Restrict binding Cluster-Admin

restrictBindingClusterAdminPolicy:
    background: false
    validationFailureAction: Enforce
    role: "!cluster-admin"


# Restriction Escalation Verbs in Roles

restrictEscalationVerbsPolicy:
  background: false
  validationFailureAction: Enforce
  verbs:
      - bind
      - impersonate
      - escalate

# Restrict access to secrets

restrictSecretAccessPolicy:
  background: false
  validationFailureAction: Enforce
  verbs:
      - list
      - view
      - get