apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-view-list-secret
  annotations:
    policies.kyverno.io/title: Restrict Secret Access
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/subject: Secrets
    policies.kyverno.io/description: >-
            This Kyverno policy is designed to restrict access to Kubernetes secrets by denying 
            specified verbs for all subjects. Specifically, the policy denies the `list`, `view`, 
            and `get` verbs for all users and service accounts, effectively preventing them from 
            accessing secrets stored in the Kubernetes cluster. 
            
spec:
  background: {{ .Values.restrictSecretAccessPolicy.background }}
  validationFailureAction: {{ .Values.restrictSecretAccessPolicy.validationFailureAction }}
  rules:
  - name: block-view-list-secret
    match:
      resources:
        kinds:
        - Secret
    validate:
      message: "Viewing or listing secrets is not allowed"
      deny:
        conditions:
        all:
        - key: "{{ `{{ request.operation }}` }}"
          operator: In
          values:
          {{- range .Values.restrictSecretAccessPolicy.verbs }}
            - {{. | quote -}}
          {{- end }}
